import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from '@/components/providers/query-provider';
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {children}
          <footer className="w-full p-4 text-center border-t text-sm text-gray-500">
              <p>© {new Date().getFullYear()} ChimeraLens AI. All Rights Reserved.</p>
              <Link href="/privacy" className="hover:underline">
                Privacy Policy
              </Link>
            </footer>
          <Toaster richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
